# Generated by Django 3.0.4 on 2021-01-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='pub_data',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.Group'),
        ),
    ]
